language: minimal

dist: bionic

sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: GHCVER=8.6.5 STACK_YAML=stack.yaml SOLVER='resolver: lts-14.1'
    addons:
      apt:
        sources:
          - sourceline: 'ppa:hvr/ghc'
        packages:
        - libblas-dev
        - liblapack-dev
        - ghc-8.6.5
  - env: GHCVER=8.4.4 STACK_YAML=stack.yaml SOLVER='resolver: lts-12.26'
    addons:
      apt:
        sources:
        - sourceline: 'ppa:hvr/ghc'
        packages:
        - libblas-dev
        - liblapack-dev
        - ghc-8.4.4

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - cd package
  - echo ${SOLVER} > stack.yaml

install:
  - stack build

script:
  - stack --no-terminal --skip-ghc-check test
