sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: GHCVER=8.6.5 STACK_YAML=stack.yaml
    addons:
      apt:
        packages:
        - libblas-dev
        - liblapack-dev
        - ghc-8.6.5

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cd package
  - stack build

script:
  - stack --no-terminal --skip-ghc-check test
